### ISSUE TITLE
Record history when people type but then don't send messages.

### ISSUE THREAD

**Issue by JaBrCo** [Morhaus/facebook-sixth-sense#1]
The notification can be hard to see when not concentrating on it and a lot of the value in seeing the typing notification disappears if they actually do send a message. I think the true value from this product at least for me would be seeing those that type but don't send, when you're not expecting them to be typing.

Someone you don't regularly chat with typing and never messaging could be a good indicator that they're open to reconnecting.

Thanks for the tool!

**Comment by alexkirsz** [comment]
Thanks for the suggestion! I might add this as an option.

In the meantime, if anyone wants to try their hand at implementing this, it looks like the `MercuryMessageStore` module is the right place to look into!

By the way, this is a really sweet way to use the app!

**Comment by bluetidepro** [comment]
+1 to @JaBrCo. I thought that was how this app WAS used. I think that's the value more, as well. It would be interesting to sort of "read someone's mind" and see when they were going to send you something but never did.

**Comment by jkingsman** [comment]
From what I saw in my testing, it does this (at least when the user has your chat open in the messages view; I didn't check if it also did it with the message popup).

**Comment by alexkirsz** [comment]
I think a good way to implement this would be to color code the typing bars when the corresponding typing led to a message.

**Comment by alexkirsz** [comment]
This is in progress over at #7. You can try this right now by building the app locally. See the [contributing instructions](https://github.com/Morhaus/facebook-sixth-sense#contributing).

**Comment by alexkirsz** [comment]
I'm closing out the repo in compliance with a Cease and Desist letter from Facebook.

![image](https://cloud.githubusercontent.com/assets/1621758/15939039/4b6c01a6-2e76-11e6-9ef8-6e963fb6e184.png)
