### ISSUE TITLE
Build fails at babel-node ./node_modules/.bin/webpack

### ISSUE THREAD

**Issue by purnimamehta** [Morhaus/facebook-sixth-sense#12]
Node and npm are up to date and I did some troubleshooting by removing and reinstalling both but this problem persisted. Any ideas?

**Comment by alexkirsz** [comment]
Hey.

Could you please provide the full output of `npm install`?

Also, what environment are you running on?

**Comment by purnimamehta** [comment]
Using OS X and this is the error I get: 

![image](https://cloud.githubusercontent.com/assets/12402896/15815313/3974d98e-2b9a-11e6-9599-5edaeb29f3aa.png)

**Comment by purnimamehta** [comment]
Ah, seems babel was the one that needed to be updated. Got it figured out now. Thanks 👍

**Comment by alexkirsz** [comment]
Looks like I forgot to add babel-preset-es2015 to package.json. Will fix later today.
