### ISSUE TITLE
opera extension?

### ISSUE THREAD

**Issue by ghost** [Morhaus/facebook-sixth-sense#2]

**Comment by alexkirsz** [comment]
Hey,

I was told that the extension works on Opera as well, although you need to install the [Download Chrome Extension](https://addons.opera.com/fr/extensions/details/download-chrome-extension-9/?display=en) extension beforehand.

Let me know if that works for you!

**Comment by samirm** [comment]
What about FF?

**Comment by ghost** [comment]
@Morhaus, it works - thanks :)

**Comment by alexkirsz** [comment]
@samirm I have no plans to support Firefox, but anyone is welcome to port the extension. The platform-specific code is rather short.

@michal-gski Glad to hear that!
