### ISSUE TITLE
Encoding issue on typing hover

### ISSUE THREAD

**Issue by alexkirsz** [Morhaus/facebook-sixth-sense#6]
Some people are encountering an encoding issue. The `–` symbol in the typing hover message is replaced with `â€"`.

![](http://i.imgur.com/KSK9RyU.png)

**Comment by tjisousa** [comment]
Same here..

**Comment by tarungarg546** [comment]
Will work on it today and may be submit a PR...

**Comment by alexkirsz** [comment]
Fixed by #11.
